// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NubeCasera.Datos;

#nullable disable

namespace NubeCasera.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("NubeCasera.Clases.ArchivoReferencia", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaDeSubida")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaDeAlmacenamiento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TamanioBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("carpetaLogicaID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("carpetaLogicaID");

                    b.ToTable("archivoReferencias");
                });

            modelBuilder.Entity("NubeCasera.Clases.Categoria", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoriaPadreID")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CategoriaPadreID");

                    b.ToTable("categorias");

                    b.HasData(
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000001"),
                            NombreCategoria = "Principal"
                        });
                });

            modelBuilder.Entity("NubeCasera.Clases.ArchivoReferencia", b =>
                {
                    b.HasOne("NubeCasera.Clases.Categoria", "carpetaLogica")
                        .WithMany("archivosReferencias")
                        .HasForeignKey("carpetaLogicaID");

                    b.Navigation("carpetaLogica");
                });

            modelBuilder.Entity("NubeCasera.Clases.Categoria", b =>
                {
                    b.HasOne("NubeCasera.Clases.Categoria", "CategoriaPadre")
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaPadreID");

                    b.Navigation("CategoriaPadre");
                });

            modelBuilder.Entity("NubeCasera.Clases.Categoria", b =>
                {
                    b.Navigation("SubCategorias");

                    b.Navigation("archivosReferencias");
                });
#pragma warning restore 612, 618
        }
    }
}
